version: '3'
services:
  jupyter:
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - .:/home/jovyan/work
    ports:
      - 8888:8888
    environment:
      - NB_UID=${NB_UID}
